travis:
  secure:
    BINSTAR_TOKEN: W/BRIvyI+rs6B6CN/w97+ZQYJV0T/VzjIHNYIk6/avcRyitdBp7pgzVPwh2woSa+FiE6HgQVbDdOgvhNZUSy1dDrBr+5UenEgVLFRTE4FZ9pc5P8Cea81ZyQqB6eTAMUlN3/PQeTaUBhzZX2JE+pyUua2vML5Se11mmalK1+fOPEh5dgP+dXgvG9K0xUcNHAKFNfYqsBuF0toxKF/unY9IHZF6EFsLTAr6mZhrU9OHodwpu4ElakFmnZIYbvKDCKz/hDz/olPj5JmkBLjstoi0vjq+P4m9wkxuJk+MXN1DobfampBlVJ8hPdMfWBOWgH5V5a+W5FyggABJynmEql/o4qiF+zkVUOd4W6SrGT2BczGe6DHUlHq4aOia+qZ6Nldk3bwwlXDVqRzqdrmAf6OupQIba5aipAqiZBLAtm7EXeklytvhSLCDyvYLC2jwQtpBOjBKfB7itiQS39EnKFh2GZ9KvgJ3gOWRpxuRz5njK9IJUb+t7LLM4eco3V6I2JdDPAl7C520vTXcoPwx6BJrV3tA9qM/f/Sxrd/VcvXmQEzNLRPWmDa8mFEU01XjMuKXC4hFedFP3Zw1awTlO6cLvTA3Q4I0NzKxdfVLdB5ZxGwt3STvXcEQMkFWmSgLEDwhugPLm9TU2lJum1RIn7DVq18tcDpUevnfnPnuJekCg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
